### ISSUE TITLE
是否可以考虑添加一个组件销毁事件

### ISSUE THREAD

**Issue by zvzuola** [zhoushengmufc/iosselect#11]
如果应用在react中，没用手动点击取消或确定，当路由改变后，改组件依然存在，所以需要一个销毁事件，在react组件销毁的时候同时把该组件也销毁。

**Comment by zhoushengmufc** [comment]
好的，后续会增加该功能

**Comment by anming-john** [comment]
请问， 现在这个功能是什么进度了， 我也遇到这个问题了

**Comment by pengweifu** [comment]
暂时请参考这个wiki 
[manual close component](https://github.com/zhoushengmufc/iosselect/wiki/manual-close-component)

**Comment by anming-john** [comment]
还有一个问题， 我每次点击，显示select 面板， 都是通过新 new 一个实例来实现， 有没有类似， show, close  的方法

**Comment by pengweifu** [comment]
#70
