### ISSUE TITLE
ios取消和确定按钮掉下去了

### ISSUE THREAD

**Issue by bryanLiny** [zhoushengmufc/iosselect#13]
IOS微信浏览器测试，“取消”和“确定”按钮掉到滚动选择面上了，我的IOS的9.3.5

**Comment by zhoushengmufc** [comment]
样式问题，你可以调试下，然后把解决方法给我，谢谢

**Comment by bryanLiny** [comment]
原'<h2 id="iosSelectTitle"></h2>'改成'<span id="iosSelectTitle"></span>'即可

**Comment by bryanLiny** [comment]
原 `<h2 id="iosSelectTitle"></h2>` 改成 `<span id="iosSelectTitle"></span>`

**Comment by necrodiver** [comment]
可以把`<h2 id="iosSelectTitle"></h2>`往后挪一下，放在取消和确定标签中间,样式没什么问题

**Comment by pengweifu** [comment]
新的master分支已经按照 @necrodiver  的方法改过来了
