### ISSUE TITLE
1.建议加上选择组件上滑和背景透明度渐变动画；2.点击非选择器地方自动下滑隐藏。

### ISSUE THREAD

**Issue by rzdong** [zhoushengmufc/iosselect#22]
1.我使用过程中实现了题目的描述，写了点css3，自己用也就够了； 另外就是题目的第二个，组件隐藏目前只能通过点击取消和确定按钮，如果能点击半透明的背景隐藏就更棒了。

**Comment by pengweifu** [comment]
点击遮罩层下滑隐藏和入场动画在master分支里面加上了哦
