### ISSUE TITLE
在页面高度大于viewport的时候点击select会跳回页面顶部

### ISSUE THREAD

**Issue by MinuteWong** [zhoushengmufc/iosselect#29]
iosSelect.js 258 window.scrollTo(0,0)去掉,css文件中的ios-select-body-class改为`.ios-select-body-class{overflow:hidden}`可以解决,不知道作者的scrollTo(0,0)的意图是什么

**Comment by pengweifu** [comment]
加上ios-select-body-class这个class以后 body的高度就和视口一样高啦 
这样就导致跳回页面顶部了，并不是因为window.scrollTo(0,0)
其实这句没什么意义，在滚动之前，页面其实已经到顶部了
