### ISSUE TITLE
组件是否支持点击列表选中事件

### ISSUE THREAD

**Issue by sirius007** [zhoushengmufc/iosselect#40]
![image](https://user-images.githubusercontent.com/12542737/30892943-f836ccd2-a36d-11e7-9d07-a027a02ebe9b.png)
当我点击天津或者河北的时候，可以滚动为选中列吗？应该如何设置，谢谢

**Comment by pengweifu** [comment]
默认是不可以的哦，这个插件适用于手持设备，滑动操作也挺方便的呀
你可以尝试修改源代码 增加点击事件

**Comment by sirius007** [comment]
建议添加上 ，因为ios原生上既可以滑动又可以点选
