### ISSUE TITLE
addClassName 这个OPTION怎么用？

### ISSUE THREAD

**Issue by sunszl** [zhoushengmufc/iosselect#52]
我发现 .close 和BOOTSTRAP 的冲突了。
导致按钮变得很暗。

可否说明下这个addClassName怎么用？看说明是用来自定义CSS名的。
谢谢。

**Comment by zhoushengmufc** [comment]
addclassname是添加在组件最外层的class，你可以覆盖内部class样式

**Comment by sunszl** [comment]
谢谢


在2018年10月19日 11:41，zhousheng<notifications@github.com> 写道：

addclassname是添加在组件最外层的class，你可以覆盖内部class样式
