### ISSUE TITLE
三级城市联动，直辖市显示有问题

### ISSUE THREAD

**Issue by Kennersky** [zhoushengmufc/iosselect#53]
![tim 20181024144343](https://user-images.githubusercontent.com/2129521/47411422-3db56180-d79b-11e8-9059-989ee8b9dc85.png)

如图，北京市 下级 就直接到城区了，变成又多了一个北京市，这个怎么修改才能让它当是直辖市的时候不显示第三级，第二级自动变成城区

**Comment by pengweifu** [comment]
目前只能这样子
