### ISSUE TITLE
滑动问题

### ISSUE THREAD

**Issue by shichengyu921228** [zhoushengmufc/iosselect#64]
首先感谢大佬的分享  其次有个问题想请教一下  我用微信开发工具打开的公众号网页引用了 下拉之后  发现 无法滑动  把页面在谷歌上打开可以滑动  而用微信开发工具打开的公众号网页上没办法滑动  请问应该怎么处理?

**Comment by gaga-change** [comment]
在插件引用前调用的。目的为了把企业微信内置浏览器window对象的ontouchstart删了。针对当时我使用的版本。https://github.com/zhoushengmufc/iosselect/issues/47#issue-338144727

**Comment by shichengyu921228** [comment]
我用的是最新的版本 在插件引用之前调用 发现没有效果  if (~navigator.userAgent.toLowerCase().indexOf('windowswechat')) {
	delete window.ontouchstart
}
这个 并没有生效  打印是 undefined

**Comment by gaga-change** [comment]
```html
<script>
if (~navigator.userAgent.toLowerCase().indexOf('windowswechat')) {
  delete window.ontouchstart
}
</script>
放在html 顶部试试
```

**Comment by shichengyu921228** [comment]
不行  还是没反应  我是在微信开发者工具里的公众号网页打开的  没有反应  ~navigator.userAgent.toLowerCase().indexOf('windowswechat')   打印是  0

**Comment by shichengyu921228** [comment]
不行  还是没反应  我是在微信开发者工具里的公众号网页打开的  没有反应  ~navigator.userAgent.toLowerCase().indexOf('windowswechat')   打印是  0

**Comment by gaga-change** [comment]
> 不行 还是没反应 我是在微信开发者工具里的公众号网页打开的 没有反应 ~navigator.userAgent.toLowerCase().indexOf('windowswechat') 打印是 0

好吧，那就不是同一个问题了

**Comment by shichengyu921228** [comment]
好吧  谢谢了  我在谷歌模拟 微信浏览器 就可以滑动  但是在微信开发工具上就不行

**Comment by zhoushengmufc** [comment]
由于工作较忙，没时间修复这个问题，欢迎提供解决方案，我合并到master里

**Comment by pengweifu** [comment]
window.ontouchstart 在开发者工具中判断为false，实际是支持的
解决方案：

在iosselect.js文件中搜索 
> var _transform = _prefixStyle('transform');

在这行下面加代码：
> var isWechatDebug = navigator.userAgent.toLowerCase().indexOf('wechatdevtools') > -1;

并将这行下面的第五行
> hasTouch: 'ontouchstart' in window,

修改为
> hasTouch: 'ontouchstart' in window || isWechatDebug,

**Comment by shichengyu921228** [comment]
多谢
