### ISSUE TITLE
在触摸屏设备上滑动有时会卡住

### ISSUE THREAD

**Issue by yihuan** [zhoushengmufc/iosselect#73]
我在触摸屏上操作的时候，有时滑动菜单就会卡住无法滑动，概率很大。但通过鼠标点击或者打开Chrome的模拟器也很少出现这个问题，不过偶尔也会出现。请问可能是因为什么原因？

**Comment by pengweifu** [comment]
> 我在触摸屏上操作的时候，有时滑动菜单就会卡住无法滑动，概率很大。但通过鼠标点击或者打开Chrome的模拟器也很少出现这个问题，不过偶尔也会出现。请问可能是因为什么原因？

触摸屏 具体是什么型号?

**Comment by yihuan** [comment]
不好意思，当时是对方的人自己测的，也没说清楚具体什么型号。大概的意思是通过什么设备让普通屏幕具有可触摸的功能。但我在其他设备上测试是没有问题的。
